version: '3.1'
services:
  rabbitmq:
    hostname: "rabbitmq"
    image: rabbitmq:3-alpine
    ports:
      - 15672:15672
      - 5673:5672
    networks:
      - credit_request_network
  redis:
    hostname: "redis"
    image: redis:5-alpine
    ports:
      - 6379:6379
    networks:
      - credit_request_network
  app:
    hostname: "app"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - rabbitmq
      - redis
    networks:
      - credit_request_network

networks:
  credit_request_network:
    driver: bridge