
version: "3.2"
services:

  redis:
    hostname: redis
    container_name: redis
    image: redis:5-alpine
    ports:
      - '6379:6379'

  rabbit_mq:
    image: rabbitmq:3.8-rc-management
    container_name: rabbit_mq
    ports:
        - '5672:5672'
        - '15672:15672'
    volumes:
      - rabbit_mqdata:/usr/share/rabbitmq/data

  producer:
    build: producer
    ports:
      - '8000:8000'
    depends_on:
        - rabbit_mq
    environment:
        AMQP_URL: 'amqp://rabbit_mq?connection_attempts=5&retry_delay=5'
    volumes:
      - ./producer:/usr/src/app/producer

  consumer_age:
    build: consumer_age
    depends_on:
        - rabbit_mq
    environment:
        AMQP_URL: 'amqp://rabbit_mq?connection_attempts=1&retry_delay=1'
    volumes:
      - ./consumer_age:/usr/src/app/consumer_age

  consumer_value:
    build: consumer_value
    depends_on:
        - rabbit_mq
    environment:
        AMQP_URL: 'amqp://rabbit_mq?connection_attempts=1&retry_delay=1'
    volumes:
      - ./consumer_value:/usr/src/app/consumer_value

volumes:
    rabbit_mqdata:
      driver: local
